export enum ViewState {
  LOGIN = 'LOGIN',
  PUBLIC_SERVICES = 'PUBLIC_SERVICES',
  SCANNER = 'SCANNER',
  NEWS = 'NEWS',
  DASHBOARD = 'DASHBOARD',
  GUEST_DASHBOARD = 'GUEST_DASHBOARD',
  DEVELOPER = 'DEVELOPER',
  KANWIL_DASHBOARD = 'KANWIL_DASHBOARD',
  KANWIL_SATUAN_KERJA = 'KANWIL_SATUAN_KERJA',
  DEV_ASSIGNMENTS = 'DEV_ASSIGNMENTS',
  DEV_ROLES = 'DEV_ROLES',
  DEV_PERMISSIONS = 'DEV_PERMISSIONS',
  DEV_SYNC = 'DEV_SYNC',
  DEV_AUDIT_LOG = 'DEV_AUDIT_LOG',
  DEV_SECURITY = 'DEV_SECURITY',
  DEV_SYSTEM_SETTINGS = 'DEV_SYSTEM_SETTINGS',
  DEVELOPER_CONSOLE = 'DEVELOPER_CONSOLE',
  STUDENTS = 'STUDENTS',
  PROFILE = 'PROFILE',
}
export interface TickerItem {
  id: string;
  isActive: boolean;
}
