// src/types/permissions.ts

import { UserRole } from './roles';

/**
 * Enterprise Permission Registry.
 * Fine-grained permissions defining what actions users can execute on system resources.
 */
export const PERMISSIONS = {
  // Students
  STUDENT_READ: 'student.read',
  STUDENT_CREATE: 'student.create',
  STUDENT_UPDATE: 'student.update',
  STUDENT_DELETE: 'student.delete',

  // Teachers
  TEACHER_READ: 'teacher.read',
  TEACHER_CREATE: 'teacher.create',
  TEACHER_UPDATE: 'teacher.update',
  TEACHER_DELETE: 'teacher.delete',

  // Attendance
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_WRITE: 'attendance.write',
  ATTENDANCE_VERIFY: 'attendance.verify',
  ATTENDANCE_DELETE: 'attendance.delete',

  // Point System
  POINT_READ: 'point.read',
  POINT_WRITE: 'point.write',

  // News / Announcement
  NEWS_READ: 'news.read',
  NEWS_WRITE: 'news.write',

  // Official Letters
  LETTER_READ: 'letter.read',
  LETTER_SUBMIT: 'letter.submit',
  LETTER_APPROVE: 'letter.approve',

  // PTSP (Service Center)
  PTSP_READ: 'ptsp.read',
  PTSP_SUBMIT: 'ptsp.submit',
  PTSP_APPROVE: 'ptsp.approve',

  // Academic / Classes
  CLASS_READ: 'class.read',
  CLASS_CREATE: 'class.create',
  CLASS_UPDATE: 'class.update',
  CLASS_DELETE: 'class.delete',
  CLASS_WRITE: 'class.write',

  // Chat / Messages
  CHAT_READ: 'chat.read',
  CHAT_WRITE: 'chat.write',

  // System Administration & Workspaces
  SYSTEM_MIGRATION: 'system.migration',
  SYSTEM_CONFIG: 'system.config',
  AUDIT_LOG_READ: 'audit.read',
  DEVELOPER_CONSOLE: 'developer.console',

  // Module Permissions
  MODULE_DEVELOPER: 'developer.access',
  MODULE_KANWIL: 'kanwil.access',
  MODULE_KEMENAG: 'kemenag.access',
  MODULE_MADRASAH: 'madrasah.access',
  MODULE_DASHBOARD: 'dashboard.access',
  MODULE_SETTINGS: 'settings.access',

  // Feature Permissions - Developer Workspace
  DEVELOPER_SCHEMA_READ: 'developer.schema.read',
  DEVELOPER_BROADCAST_READ: 'developer.broadcast.read',
  DEVELOPER_MIGRATION_EXECUTE: 'developer.migration.execute',
  DEVELOPER_AUDIT_READ: 'developer.audit.read',

  // Feature Permissions - Kanwil Workspace
  KANWIL_INSTANSI_READ: 'kanwil.instansi.read',
  KANWIL_MONITORING_READ: 'kanwil.monitoring.read',
  KANWIL_USER_READ: 'kanwil.user.read',
  KANWIL_LAPORAN_READ: 'kanwil.laporan.read',

  // Feature Permissions - Kemenag Workspace
  KEMENAG_MADRASAH_READ: 'kemenag.madrasah.read',
  KEMENAG_GURU_READ: 'kemenag.guru.read',
  KEMENAG_SISWA_READ: 'kemenag.siswa.read',
  KEMENAG_MONITORING_READ: 'kemenag.monitoring.read',
  KEMENAG_LAPORAN_READ: 'kemenag.laporan.read',

  // Feature Permissions - Madrasah Workspace
  MADRASAH_AKADEMIK_READ: 'madrasah.akademik.read',
  MADRASAH_PRESENSI_READ: 'madrasah.presensi.read',
  MADRASAH_KEPEGAWAIAN_READ: 'madrasah.kepegawaian.read',
  MADRASAH_BK_READ: 'madrasah.bk.read',
  MADRASAH_ADMINISTRASI_READ: 'madrasah.administrasi.read',
  
  // Users
  USER_READ: 'user.read',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  
  ALL: 'all',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Role-Permission Registry mapping each system role to its authorized scopes.
 */
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.DEVELOPER]: Object.values(PERMISSIONS) as Permission[],
  [UserRole.KANWIL]: [
    PERMISSIONS.MODULE_DASHBOARD,
    PERMISSIONS.MODULE_KANWIL,
    PERMISSIONS.MODULE_SETTINGS,
  ],

  [UserRole.KANKEMENAG]: [
    PERMISSIONS.MODULE_DASHBOARD,
    PERMISSIONS.MODULE_KEMENAG,
    PERMISSIONS.MODULE_SETTINGS,
  ],

  [UserRole.ADMIN]: [
    PERMISSIONS.MODULE_DASHBOARD,
    PERMISSIONS.MODULE_MADRASAH,
    PERMISSIONS.MODULE_KANWIL,
    PERMISSIONS.MODULE_KEMENAG,
    PERMISSIONS.MODULE_SETTINGS,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.TEACHER_DELETE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ATTENDANCE_VERIFY,
    PERMISSIONS.ATTENDANCE_DELETE,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.PTSP_APPROVE,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_WRITE,
    PERMISSIONS.SYSTEM_CONFIG,
    PERMISSIONS.AUDIT_LOG_READ,
  ],

  [UserRole.ADMIN_MADRASAH]: [
    PERMISSIONS.MODULE_DASHBOARD,
    PERMISSIONS.MODULE_MADRASAH,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ATTENDANCE_VERIFY,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.PTSP_APPROVE,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_WRITE,
    PERMISSIONS.AUDIT_LOG_READ,
  ],

  [UserRole.KEPALA_MADRASAH]: [
    PERMISSIONS.MODULE_DASHBOARD,
    PERMISSIONS.MODULE_MADRASAH,
    PERMISSIONS.MODULE_KANWIL,
    PERMISSIONS.MODULE_KEMENAG,
    PERMISSIONS.MODULE_SETTINGS,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.AUDIT_LOG_READ,
  ],

  [UserRole.KEPALA_TU]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.PTSP_APPROVE,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.WAKAMAD]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.PTSP_APPROVE,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.KESISWAAN]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ATTENDANCE_VERIFY,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.KURIKULUM]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
  ],

  [UserRole.GTK]: [
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.TEACHER_DELETE,
  ],

  [UserRole.GURU_BK]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
  ],

  [UserRole.BK]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
  ],

  [UserRole.STAF]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.PTSP_SUBMIT,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.WALI_KELAS]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ATTENDANCE_VERIFY,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.GURU]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.PENGURUS_ASRAMA]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
  ],

  [UserRole.ORANG_TUA]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_SUBMIT,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.PTSP_SUBMIT,
  ],

  [UserRole.SISWA]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.PTSP_READ,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.BENDAHARA]: [PERMISSIONS.STUDENT_READ, PERMISSIONS.CLASS_READ],

  [UserRole.SARPRAS]: [PERMISSIONS.CLASS_READ],

  [UserRole.HUMAS]: [PERMISSIONS.NEWS_READ, PERMISSIONS.NEWS_WRITE],

  [UserRole.PUSTAKAWAN]: [PERMISSIONS.STUDENT_READ],

  [UserRole.SATPAM]: [PERMISSIONS.STUDENT_READ, PERMISSIONS.ATTENDANCE_READ],

  [UserRole.LABORAN]: [PERMISSIONS.CLASS_READ],

  [UserRole.PEMBINA_OSIS]: [PERMISSIONS.POINT_READ, PERMISSIONS.POINT_WRITE],

  [UserRole.ALUMNI]: [PERMISSIONS.NEWS_READ],

  [UserRole.TAMU]: [PERMISSIONS.NEWS_READ],

  [UserRole.STAF_TU]: [PERMISSIONS.STUDENT_READ, PERMISSIONS.TEACHER_READ],

  [UserRole.KETUA_KELAS]: [PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_WRITE],

  [UserRole.SUPER_ADMIN]: Object.values(PERMISSIONS) as Permission[],

  [UserRole.ADMIN_OPERASIONAL]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.CLASS_READ,
  ],

  [UserRole.PEMBINA_EKSKUL]: [PERMISSIONS.STUDENT_READ, PERMISSIONS.POINT_WRITE],

  [UserRole.PIKET]: [PERMISSIONS.STUDENT_READ, PERMISSIONS.ATTENDANCE_WRITE],

  [UserRole.KOMITE]: [PERMISSIONS.NEWS_READ],
};

/**
 * Helper utility to verify if a given role has the requested permission scope.
 */
export function hasPermission(role: UserRole, permission: Permission): boolean {
  const allowed = ROLE_PERMISSIONS[role as UserRole];
  if (!allowed) return false;
  return allowed.includes(permission);
}
