import { UserRole } from './roles';

export const PERMISSIONS = {
  // Developer & System
  DEVELOPER_CONSOLE: 'developer.console',
  DEVELOPER_ACCESS: 'developer.access',
  DEVELOPER_MIGRATE: 'developer.migrate',
  DEVELOPER_REPAIR: 'developer.repair',

  // Tenant / Regional
  KANWIL_ACCESS: 'kanwil.access',
  KEMENAG_ACCESS: 'kemenag.access',

  // User & Identity
  USER_READ: 'user.read',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_IMPERSONATE: 'user.impersonate',

  // Student
  STUDENT_READ: 'student.read',
  STUDENT_CREATE: 'student.create',
  STUDENT_UPDATE: 'student.update',
  STUDENT_DELETE: 'student.delete',

  // Teacher
  TEACHER_READ: 'teacher.read',
  TEACHER_CREATE: 'teacher.create',
  TEACHER_UPDATE: 'teacher.update',
  TEACHER_DELETE: 'teacher.delete',

  // Class
  CLASS_READ: 'class.read',
  CLASS_CREATE: 'class.create',
  CLASS_UPDATE: 'class.update',
  CLASS_DELETE: 'class.delete',
  CLASS_WRITE: 'class.write',

  // Attendance
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_WRITE: 'attendance.write',
  ATTENDANCE_VERIFY: 'attendance.verify',

  // Letters
  LETTER_READ: 'letter.read',
  LETTER_CREATE: 'letter.create',
  LETTER_APPROVE: 'letter.approve',
  LETTER_DELETE: 'letter.delete',

  // Points / BK
  POINT_READ: 'point.read',
  POINT_WRITE: 'point.write',
  POINT_DELETE: 'point.delete',
  BK_READ: 'bk.read',
  BK_WRITE: 'bk.write',

  // Settings
  SETTINGS_READ: 'settings.read',
  SETTINGS_WRITE: 'settings.write',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS] | string;

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  [UserRole.DEVELOPER]: Object.values(PERMISSIONS),
  [UserRole.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [UserRole.ADMIN]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_CREATE,
    PERMISSIONS.CLASS_UPDATE,
    PERMISSIONS.CLASS_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ATTENDANCE_VERIFY,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_CREATE,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
  ],
  [UserRole.ADMIN_MADRASAH]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_CREATE,
    PERMISSIONS.CLASS_UPDATE,
    PERMISSIONS.CLASS_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_CREATE,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [UserRole.KEPALA_MADRASAH]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [UserRole.KEPALA_TU]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_CREATE,
    PERMISSIONS.LETTER_APPROVE,
  ],
  [UserRole.STAF_TU]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_CREATE,
  ],
  [UserRole.GURU]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
  ],
  [UserRole.WALI_KELAS]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.LETTER_READ,
  ],
  [UserRole.GURU_BK]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.POINT_DELETE,
    PERMISSIONS.BK_READ,
    PERMISSIONS.BK_WRITE,
  ],
  [UserRole.BK]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.CLASS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.POINT_READ,
    PERMISSIONS.POINT_WRITE,
    PERMISSIONS.BK_READ,
    PERMISSIONS.BK_WRITE,
  ],
  [UserRole.SISWA]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_CREATE,
    PERMISSIONS.POINT_READ,
  ],
  [UserRole.ORANG_TUA]: [
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.POINT_READ,
  ],
  [UserRole.KANWIL]: [
    PERMISSIONS.KANWIL_ACCESS,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.CLASS_READ,
  ],
  [UserRole.KEMENAG]: [
    PERMISSIONS.KEMENAG_ACCESS,
    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.CLASS_READ,
  ],
};

export function hasPermission(role: UserRole | string, permission: Permission): boolean {
  const allowed = ROLE_PERMISSIONS[role] || [];
  return allowed.includes(permission) || allowed.includes(PERMISSIONS.DEVELOPER_ACCESS);
}
