import { ViewState, UserRole } from '@/types';
import { NavTabConfig } from './navigation.types';
import {
  HomeIcon,
  BuildingLibraryIcon,
  Squares2x2Icon,
  CogIcon,
  UserIcon,
  UsersIcon,
  CalendarDaysIcon,
  ClockIcon,
  StarIcon,
  EnvelopeIcon,
  ChartBarIcon,
  RectangleStackIcon,
} from '@/shared/Icons';

export const ROLE_BOTTOM_NAV: Partial<Record<UserRole, NavTabConfig[]>> = {
  [UserRole.DEVELOPER]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.DEVELOPER, label: 'Console', icon: Squares2x2Icon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.SUPER_ADMIN]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.USERS, label: 'Pengguna', icon: UsersIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.ADMIN]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.USERS, label: 'Pengguna', icon: UsersIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.ADMIN_MADRASAH]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.USERS, label: 'Pengguna', icon: UsersIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.KANWIL]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.KEMENAG_HUB, label: 'Kemenag', icon: BuildingLibraryIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.REPORTS, label: 'Laporan', icon: ChartBarIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.KEPALA_MADRASAH]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.LETTERS, label: 'Surat', icon: EnvelopeIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.KEPALA_TU]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.LETTERS, label: 'Surat', icon: EnvelopeIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.GURU]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.CLASSES, label: 'Kelasku', icon: UsersIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.WALI_KELAS]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.CLASSES, label: 'Kelasku', icon: UsersIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.GURU_BK]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.POINTS, label: 'Poin', icon: StarIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.KESISWAAN]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.POINTS, label: 'Poin', icon: StarIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.STAF]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.LETTERS, label: 'Surat', icon: EnvelopeIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.STAF_TU]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.LETTERS, label: 'Surat', icon: EnvelopeIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.SISWA]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.SCHEDULE, label: 'Jadwal', icon: CalendarDaysIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.ORANG_TUA]: [
    { view: ViewState.DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.ATTENDANCE_HISTORY, label: 'Presensi', icon: ClockIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.STUDENTS, label: 'Anak', icon: UserIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
  [UserRole.TAMU]: [
    { view: ViewState.GUEST_DASHBOARD, label: 'Home', icon: HomeIcon },
    { view: ViewState.PUBLIC_SERVICES, label: 'Layanan', icon: EnvelopeIcon },
    { view: ViewState.ALL_FEATURES, label: 'SEMUA', icon: RectangleStackIcon },
    { view: ViewState.MADRASAH_INFO, label: 'Madrasah', icon: BuildingLibraryIcon },
    { view: ViewState.PROFILE, label: 'Profil', icon: UserIcon },
  ],
};
