export const MASTER_PERMISSIONS = {
  SYSTEM_MANAGE: 'system.manage',
  TENANT_MANAGE: 'tenant.manage',
  MIGRATION_EXECUTE: 'migration.execute',
  DATABASE_AUDIT: 'database.audit',
  USER_OVERRIDE: 'user.override',

  USER_VIEW: 'user.view',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_ASSIGN_ROLE: 'user.assign_role',

  ROLE_ASSIGN: 'role.assign',
  PERMISSION_VIEW: 'permission.view',
  PERMISSION_MANAGE: 'permission.manage',

  STUDENT_VIEW: 'student.view',
  STUDENT_CREATE: 'student.create',
  STUDENT_UPDATE: 'student.update',
  STUDENT_DELETE: 'student.delete',
  STUDENT_MANAGE: 'student.manage',

  TEACHER_VIEW: 'teacher.view',
  TEACHER_CREATE: 'teacher.create',
  TEACHER_UPDATE: 'teacher.update',
  TEACHER_DELETE: 'teacher.delete',
  TEACHER_MANAGE: 'teacher.manage',

  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_CREATE: 'attendance.create',
  ATTENDANCE_UPDATE: 'attendance.update',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_APPROVE: 'attendance.approve',

  LETTER_VIEW: 'letter.view',
  LETTER_CREATE: 'letter.create',
  LETTER_REVIEW: 'letter.review',
  LETTER_APPROVE: 'letter.approve',
  LETTER_MANAGE: 'letter.manage',

  REPORT_VIEW: 'report.view',
  AUDIT_VIEW: 'audit.view',
  APPROVAL_MANAGE: 'approval.manage',
  CLASS_MANAGE: 'class.manage',
  CLASS_VIEW: 'class.view',
  CLASS_CREATE: 'class.create',
  CLASS_UPDATE: 'class.update',
  CLASS_DELETE: 'class.delete',
  CLASS_ASSIGN_TEACHER: 'class.assign_teacher',
  CLASS_ASSIGN_STUDENT: 'class.assign_student',
  CLASS_EXPORT: 'class.export',

  MADRASAH_VIEW: 'madrasah.view',
  MADRASAH_CREATE: 'madrasah.create',
  MADRASAH_UPDATE: 'madrasah.update',
  MADRASAH_DELETE: 'madrasah.delete',
  MADRASAH_RESTORE: 'madrasah.restore',
} as const;

export type Permission = typeof MASTER_PERMISSIONS[keyof typeof MASTER_PERMISSIONS] | string;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  developer: [
    'system.manage',
    'tenant.manage',
    'migration.execute',
    'database.audit',
    'user.override',
    'user.view',
    'user.create',
    'user.update',
    'user.delete',
    'user.assign_role',
    'role.assign',
    'permission.view',
    'permission.manage',
    'audit.view',
    'class.view',
    'class.create',
    'class.update',
    'class.delete',
    'class.assign_teacher',
    'class.assign_student',
    'class.export',
    'madrasah.view',
    'madrasah.create',
    'madrasah.update',
    'madrasah.delete',
    'madrasah.restore',
  ],
  admin: [
    'user.view',
    'user.create',
    'user.update',
    'user.delete',
    'user.assign_role',
    'role.assign',
    'permission.view',
    'permission.manage',
    'class.manage',
    'class.view',
    'class.create',
    'class.update',
    'class.delete',
    'class.assign_teacher',
    'class.assign_student',
    'class.export',
    'approval.manage',
    'report.view',
    'audit.view',
    'student.view',
    'student.create',
    'student.update',
    'student.delete',
    'teacher.view',
    'teacher.create',
    'teacher.update',
    'teacher.delete',
  ],
  kamad: [
    'report.view',
    'approval.manage',
    'letter.review',
    'letter.approve',
    'attendance.view',
    'student.view',
    'teacher.view',
    'audit.view',
    'class.view',
    'class.export',
  ],
  wakamad: [
    'report.view',
    'approval.manage',
    'class.manage',
    'class.view',
    'class.create',
    'class.update',
    'class.assign_teacher',
    'class.export',
    'attendance.view',
    'student.view',
    'teacher.view',
  ],
  keptu: [
    'letter.create',
    'letter.review',
    'letter.manage',
    'user.view',
    'report.view',
    'class.view',
  ],
  guru: [
    'attendance.view',
    'attendance.create',
    'attendance.update',
    'student.view',
    'report.view',
    'class.view',
  ],
  wali_kelas: [
    'attendance.view',
    'attendance.create',
    'attendance.update',
    'student.view',
    'student.update',
    'report.view',
    'class.view',
    'class.update',
  ],
  guru_bk: [
    'student.view',
    'student.update',
    'report.view',
    'class.view',
  ],
  staf: [
    'student.view',
    'teacher.view',
    'attendance.view',
    'letter.create',
    'report.view',
    'class.view',
  ],
  siswa: [
    'student.view',
    'attendance.view',
    'letter.create',
    'class.view',
  ],
  ketua_kelas: [
    'student.view',
    'attendance.view',
    'attendance.create',
    'letter.create',
    'class.view',
  ],
  orang_tua: [
    'student.view',
    'attendance.view',
    'report.view',
    'class.view',
  ],
  guest: [],
};
