import * as Icons from '@/shared/Icons';

export const TABEL_SISTEM = [
  {
    id: 'academic_years',
    label: 'Tahun Akademik',
    icon: Icons.CalendarIcon,
    color: 'text-blue-500',
  },
  { id: 'ai_logs', label: 'AI Logs', icon: Icons.SparklesIcon, color: 'text-indigo-400' },
  { id: 'alumni', label: 'Alumni', icon: Icons.BriefcaseIcon, color: 'text-emerald-700' },
  { id: 'assignments', label: 'Tugas & PR', icon: Icons.BookOpenIcon, color: 'text-amber-500' },
  { id: 'attendance', label: 'Presensi Siswa', icon: Icons.ClockIcon, color: 'text-emerald-500' },
  {
    id: 'attendance_configs',
    label: 'Config Jendela Absen',
    icon: Icons.ShieldCheckIcon,
    color: 'text-indigo-400',
  },
  { id: 'audit_logs', label: 'Audit Logs', icon: Icons.CommandLineIcon, color: 'text-slate-500' },
  {
    id: 'audit_notifications',
    label: 'Notifikasi Audit',
    icon: Icons.BellIcon,
    color: 'text-amber-500',
  },
  { id: 'chats', label: 'Chats', icon: Icons.MessageCircleIcon, color: 'text-sky-500' },
  {
    id: 'classes',
    label: 'Kelas/Rombel',
    icon: Icons.BuildingLibraryIcon,
    color: 'text-indigo-500',
  },
  {
    id: 'daily_stats',
    label: 'Statistik Harian',
    icon: Icons.ChartBarIcon,
    color: 'text-rose-500',
  },
  { id: 'documentation', label: 'Dokumentasi', icon: Icons.InfoIcon, color: 'text-sky-400' },
  { id: 'events', label: 'Kalender Agenda', icon: Icons.CalendarIcon, color: 'text-violet-400' },
  { id: 'letters', label: 'Letters (Surat)', icon: Icons.MegaphoneIcon, color: 'text-blue-400' },
  { id: 'liveChat', label: 'Live Chat', icon: Icons.MessageCircleIcon, color: 'text-emerald-400' },
  { id: 'login_logs', label: 'Log Login', icon: Icons.KeyIcon, color: 'text-orange-500' },
  { id: 'logs', label: 'Log Whatsapp/System', icon: Icons.CommandLineIcon, color: 'text-zinc-600' },
  { id: 'metadata', label: 'Metadata App', icon: Icons.InfoIcon, color: 'text-cyan-500' },
  {
    id: 'migration_backups',
    label: 'Backup Migrasi',
    icon: Icons.RectangleStackIcon,
    color: 'text-purple-500',
  },
  {
    id: 'migration_logs',
    label: 'Log Migrasi',
    icon: Icons.CommandLineIcon,
    color: 'text-gray-400',
  },
  { id: 'mutasi', label: 'Mutasi Siswa', icon: Icons.ArrowPathIcon, color: 'text-rose-600' },
  { id: 'news', label: 'Berita & Artikel', icon: Icons.MegaphoneIcon, color: 'text-teal-500' },
  { id: 'notifications', label: 'Push Notif', icon: Icons.BellIcon, color: 'text-red-500' },
  { id: 'poin', label: 'Log Poin (Global)', icon: Icons.StarIcon, color: 'text-yellow-500' },
  {
    id: 'point_categories',
    label: 'Kategori Poin',
    icon: Icons.Squares2x2Icon,
    color: 'text-amber-600',
  },
  {
    id: 'presence_summary',
    label: 'Ringkasan Kehadiran',
    icon: Icons.ChartBarIcon,
    color: 'text-teal-600',
  },
  {
    id: 'profile_update_requests',
    label: 'Request Update Profil',
    icon: Icons.PencilIcon,
    color: 'text-pink-500',
  },
  {
    id: 'reward_redemptions',
    label: 'Penukaran Hadiah',
    icon: Icons.StarIcon,
    color: 'text-pink-600',
  },
  { id: 'schedules', label: 'Jadwal KBM', icon: Icons.BookOpenIcon, color: 'text-violet-500' },
  { id: 'settings', label: 'Pengaturan', icon: Icons.ShieldCheckIcon, color: 'text-slate-600' },
  {
    id: 'student_point_summaries',
    label: 'Ringkasan Poin Siswa',
    icon: Icons.StarIcon,
    color: 'text-orange-400',
  },
  {
    id: 'student_points',
    label: 'Poin Kedisiplinan',
    icon: Icons.StarIcon,
    color: 'text-yellow-600',
  },
  { id: 'students', label: 'Daftar Siswa', icon: Icons.UsersGroupIcon, color: 'text-blue-600' },
  {
    id: 'submissions',
    label: 'Pengumpulan Tugas',
    icon: Icons.FileSpreadsheet,
    color: 'text-emerald-600',
  },
  { id: 'summaries', label: 'Ringkasan Data', icon: Icons.ChartBarIcon, color: 'text-green-500' },
  { id: 'sweep_locks', label: 'Lock Mutasi', icon: Icons.LockIcon, color: 'text-amber-600' },
  {
    id: 'system',
    label: 'System (General)',
    icon: Icons.ShieldCheckIcon,
    color: 'text-indigo-600',
  },
  {
    id: 'system_config',
    label: 'Config Sistem (v1)',
    icon: Icons.ShieldCheckIcon,
    color: 'text-emerald-600',
  },
  {
    id: 'system_configs',
    label: 'Config Sistem (v2)',
    icon: Icons.ShieldCheckIcon,
    color: 'text-emerald-600',
  },
  {
    id: 'system_tests',
    label: 'Test Sistem',
    icon: Icons.CommandLineIcon,
    color: 'text-emerald-600',
  },
  {
    id: 'teacher_attendance',
    label: 'Presensi Guru',
    icon: Icons.ClockIcon,
    color: 'text-cyan-600',
  },
  { id: 'teachers', label: 'Guru & GTK', icon: Icons.BriefcaseIcon, color: 'text-indigo-800' },
  {
    id: 'tenants',
    label: 'Konfigurasi Tenant (Global)',
    icon: Icons.BuildingLibraryIcon,
    color: 'text-indigo-700',
  },
  { id: 'users', label: 'Akun Pengguna', icon: Icons.UserIcon, color: 'text-indigo-500' },
];

export const sccTabs = [
  {
    id: 'manajemen_organisasi',
    label: 'Manajemen Organisasi',
    icon: Icons.BuildingLibraryIcon,
    color: 'bg-emerald-600',
  },
  {
    id: 'manajemen_user',
    label: 'Manajemen User (IAM)',
    icon: Icons.UsersIcon,
    color: 'bg-indigo-600',
  },
  { id: 'broadcast', label: 'Siaran Sistem', icon: Icons.MegaphoneIcon, color: 'bg-emerald-500' },
  {
    id: 'features',
    label: 'Pengaturan Fitur & RBAC',
    icon: Icons.ShieldCheckIcon,
    color: 'bg-indigo-500',
  },
  {
    id: 'master_version',
    label: 'Versi Master & Migrasi',
    icon: Icons.ArrowPathIcon,
    color: 'bg-amber-500',
  },
  {
    id: 'schema_engine',
    label: 'Mesin & Penjelajah Skema',
    icon: Icons.Squares2x2Icon,
    color: 'bg-sky-500',
  },
  {
    id: 'tenant_mgmt',
    label: 'Manajemen Tenant',
    icon: Icons.BuildingLibraryIcon,
    color: 'bg-purple-500',
  },
  {
    id: 'integration_test',
    label: 'Uji Integrasi (WA)',
    icon: Icons.CommandLineIcon,
    color: 'bg-emerald-600',
  },
  {
    id: 'user_control',
    label: 'Kontrol Pengguna & Penyamaran',
    icon: Icons.UserIcon,
    color: 'bg-pink-500',
  },
  {
    id: 'attendance_control',
    label: 'Validasi Kehadiran',
    icon: Icons.ClipboardDocumentListIcon,
    color: 'bg-rose-500',
  },
  {
    id: 'dummy_engine',
    label: 'Mesin Data Dummy',
    icon: Icons.SparklesIcon,
    color: 'bg-violet-600',
  },
  { id: 'point_engine', label: 'Poin Omni', icon: Icons.StarIcon, color: 'bg-orange-500' },
  {
    id: 'audit_test',
    label: 'Audit & Validasi Sistem',
    icon: Icons.ShieldCheckIcon,
    color: 'bg-emerald-600',
  },
  {
    id: 'firestore_gov',
    label: 'Firestore Governance Center',
    icon: Icons.RectangleStackIcon,
    color: 'bg-blue-600',
  },
  {
    id: 'manajemen_madrasah',
    label: 'Manajemen Madrasah',
    icon: Icons.BuildingLibraryIcon,
    color: 'bg-emerald-600',
  },
  {
    id: 'architecture',
    label: 'Arsitektur & Blueprint e-Mam',
    icon: Icons.CpuChipIcon,
    color: 'bg-cyan-500',
  },
];
